export const GET_ROUTER_REQUEST = "GET_ROUTER_REQUEST";
export const GET_ROUTER_SUCCESS = "GET_ROUTER_SUCCESS";
export const GET_ROUTER_FAIL = "GET_ROUTER_FAIL";

export const GET_FACTORY_REQUEST = "GET_FACTORY_REQUEST";
export const GET_FACTORY_SUCCESS = "GET_FACTORY_SUCCESS";
export const GET_FACTORY_FAIL = "GET_FACTORY_FAIL";

export const GET_WETH_REQUEST = "GET_WETH_REQUEST";
export const GET_WETH_SUCCESS = "GET_WETH_SUCCESS";
export const GET_WETH_FAIL = "GET_WETH_FAIL";

export const GET_TOKEN_REQUEST = "GET_TOKEN_REQUEST";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_FAIL = "GET_TOKEN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_TOKEN0_DATA_REQUEST = "GET_TOKEN0_DATA_REQUEST";
export const GET_TOKEN0_DATA_FAIL = "GET_TOKEN0_DATA_FAIL";
export const GET_TOKEN0_DATA_SUCCESS = "GET_TOKEN0_DATA_SUCCESS";

export const GET_TOKEN1_DATA_REQUEST = "GET_TOKEN1_DATA_REQUEST";
export const GET_TOKEN1_DATA_FAIL = "GET_TOKEN1_DATA_FAIL";
export const GET_TOKEN1_DATA_SUCCESS = "GET_TOKEN1_DATA_SUCCESS";

export const GET_MY_POOLED_ASSETS_REQUEST = "GET_MY_POOLED_ASSETS_REQUEST";
export const GET_MY_POOLED_ASSETS_SUCCESS = "GET_MY_POOLED_ASSETS_SUCCESS";
export const GET_MY_POOLED_ASSETS_FAIL = "GET_MY_POOLED_ASSETS_FAIL";

export const GET_POOL_ASSETS_REQUEST = "GET_POOL_ASSETS_REQUEST";
export const GET_POOL_ASSETS_SUCCESS = "GET_POOL_ASSETS_SUCCESS";
export const GET_POOL_ASSETS_FAIL = "GET_POOL_ASSETS_FAIL";

// export const GET_TOKEN0_DATA_UNAUTH_REQUEST = "GET_TOKEN0_DATA_UNAUTH_REQUEST";
// export const GET_TOKEN0_DATA_UNAUTH_FAIL = "GET_TOKEN0_DATA_UNAUTH_FAIL";
// export const GET_TOKEN0_DATA_UNAUTH_SUCCESS = "GET_TOKEN0_DATA_UNAUTH_SUCCESS";

// export const GET_TOKEN1_DATA_UNAUTH_REQUEST = "GET_TOKEN1_DATA_UNAUTH_REQUEST";
// export const GET_TOKEN1_DATA_UNAUTH_FAIL = "GET_TOKEN1_DATA_UNAUTH_FAIL";
// export const GET_TOKEN1_DATA_UNAUTH_SUCCESS = "GET_TOKEN1_DATA_UNAUTH_SUCCESS";

// export const GET_TOKEN0_DATA_AUTH_REQUEST = "GET_TOKEN0_DATA_AUTH_REQUEST";
// export const GET_TOKEN0_DATA_AUTH_FAIL = "GET_TOKEN0_DATA_AUTH_FAIL";
// export const GET_TOKEN0_DATA_AUTH_SUCCESS = "GET_TOKEN0_DATA_AUTH_SUCCESS";

// export const GET_TOKEN1_DATA_AUTH_REQUEST = "GET_TOKEN1_DATA_AUTH_REQUEST";
// export const GET_TOKEN1_DATA_AUTH_FAIL = "GET_TOKEN1_DATA_AUTH_FAIL";
// export const GET_TOKEN1_DATA_AUTH_SUCCESS = "GET_TOKEN1_DATA_AUTH_SUCCESS";

//GET_TOKEN_BALANCE_AND_SYMBOL_REQUEST = "GET_TOKEN_BALANCE_AND_SYMBOL_REQUEST";
