export const GET_TOKEN_FROM_SELECTED_REQUEST =
  "GET_TOKEN_FROM_SELECTED_REQUEST";
export const GET_TOKEN_FROM_SELECTED_SUCCESS =
  "GET_TOKEN_FROM_SELECTED_SUCCESS";
export const GET_TOKEN_FROM_SELECTED_FAIL = "GET_TOKEN_FROM_SELECTED_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_TOKEN_TO_SELECTED_REQUEST = "GET_TOKEN_TO_SELECTED_REQUEST";
export const GET_TOKEN_TO_SELECTED_SUCCESS = "GET_TOKEN_TO_SELECTED_SUCCESS";
export const GET_TOKEN_TO_SELECTED_FAIL = "GET_TOKEN_TO_SELECTED_FAIL";

export const GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_REQUEST =
  "GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_REQUEST";
export const GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_SUCCESS =
  "GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_SUCCESS";
export const GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_FAIL =
  "GET_TOKEN_FROM_ADD_LIQUIDITY_SELECTED_FAIL";

export const GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_REQUEST =
  "GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_REQUEST";
export const GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_SUCCESS =
  "GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_SUCCESS";
export const GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_FAIL =
  "GET_TOKEN_TO_ADD_LIQUIDITY_SELECTED_FAIL";

export const GET_SLIPPAGE_REQUEST = "GET_SLIPPAGE_REQUEST";
export const GET_SLIPPAGE_SUCCESS = "GET_SLIPPAGE_SUCCESS";
export const GET_SLIPPAGE_FAIL = "GET_SLIPPAGE_FAIL";

export const GET_DEADLINE_REQUEST = "GET_DEADLINE_REQUEST";
export const GET_DEADLINE_SUCCESS = "GET_DEADLINE_SUCCESS";
export const GET_DEADLINE_FAIL = "GET_DEADLINE_FAIL";

export const GET_TRANSACTION_STATUS_REQUEST = "GET_TRANSACTION_STATUS_REQUEST";
export const GET_TRANSACTION_STATUS_SUCCESS = "GET_TRANSACTION_STATUS_SUCCESS";
export const GET_TRANSACTION_STATUS_FAIL = "GET_TRANSACTION_STATUS_FAIL";
